---
description: "자세한 정보: ' Catch ' 형식 ' '은 (는) ' system.string ' 또는 ' s t r u s. l o n <typename> s '에서 상속 된 클래스 이므로 ' ' 형식을 Catch 할 수 없습니다."
title: "'<typename>' 형식은 'System.Exception' 또는 'System.Exception'에서 상속한 클래스가 아니므로 'Catch'로 이 형식을 catch할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30392
- bc30392
helpviewer_keywords:
- BC30392
ms.assetid: 1d513d1d-38f5-4b4e-95bb-9f1209553803
ms.openlocfilehash: cc1c96e284a29f357523729bfcca1af02c693dfd
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100428404"
---
# <a name="catch-cannot-catch-type-typename-because-it-is-not-systemexception-or-a-class-that-inherits-from-systemexception"></a>'\<typename>' 형식은 'System.Exception' 또는 'System.Exception'에서 상속한 클래스가 아니므로 'Catch'로 이 형식을 catch할 수 없습니다.

`Catch` 는 예외를 가로챌 수만 있는데 예외에서 파생되지 않은 요소를 catch하려고 했습니다.  
  
 **오류 ID:** BC30392  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. `Catch` 문을 제거하거나 `Catch` 의 대상을 실제 예외로 변경합니다.  
  
## <a name="see-also"></a>참고 항목

- [Try...Catch...Finally 문](../language-reference/statements/try-catch-finally-statement.md)
