---
description: "자세한 정보: ' Catch '는 ' Try ' 문 외부에 나타날 수 없습니다."
title: "'Catch'는 'Try' 문 외부에 사용할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 4ac18a51602c7dc5c4d7b397e1b64f9ed77fcc87
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100473903"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch'는 'Try' 문 외부에 사용할 수 없습니다.

`Catch` 는 `Try...Catch...Finally` 문 블록 내에서 사용해야 합니다. 불필요한 `Catch` 문이 `Try` 블록에 있거나, `Catch` 문이 해당 `Try` 블록의 경계 외부에 나타납니다.  
  
 **오류 ID:** BC30380  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. 필요하지 않은 경우 `Catch` 문을 삭제하거나, `Try...Catch...Finally` 문 블록 내에 배치합니다.  
  
## <a name="see-also"></a>참고 항목

- [Try...Catch...Finally 문](../language-reference/statements/try-catch-finally-statement.md)
