---
description: "자세한 정보: ' Throw ' 피연산자는 ' System.object '에서 파생 되어야 합니다."
title: "'Throw' 피연산자는 'System.Exception'에서 파생되어야 합니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 9b21a9f580a23d8c21e3f25ec9cd0773bcb92345
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100477205"
---
# <a name="throw-operand-must-derive-from-systemexception"></a>'Throw' 피연산자는 'System.Exception'에서 파생되어야 합니다.

`Throw` 에 제공된 인수는 `System.Exception` 인스턴스 또는 `System.Exception`에서 파생된 클래스의 인스턴스여야 합니다.  
  
 **오류 ID:** BC30665  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
- 다음 예제와 같이 `System.Exception`에서 파생된 인수를 사용합니다.  
  
    ```vb
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>추가 정보

- [Throw 문](../language-reference/statements/throw-statement.md)
- [Try...Catch...Finally 문](../language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [.NET의 예외 처리 및 Throw](../../standard/exceptions/index.md)
