---
description: "자세한 정보: ' Catch '는 ' Try ' 문 내에서 ' Finally ' 뒤에 올 수 없습니다."
title: "'Catch'는 'Try' 문 내에서 'Finally' 뒤에 사용할 수 없습니다."
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: ec177fadf2490c3779e0ad3a1f754319e12bd9cc
ms.sourcegitcommit: 10e719780594efc781b15295e499c66f316068b8
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/14/2021
ms.locfileid: "100454952"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch'는 'Try' 문 내에서 'Finally' 뒤에 사용할 수 없습니다.

`Catch` 문이 코드에서 `Finally` 문 블록을 끝내는 `Try` 뒤에 나타납니다. `Catch` 는 `Try...Catch...Finally` 문 블록 내에서 사용해야 합니다.  
  
 **오류 ID:** BC30379  
  
## <a name="to-correct-this-error"></a>이 오류를 해결하려면  
  
1. `Catch` 문을 코드의 더 적절한 위치로 이동합니다.  
  
## <a name="see-also"></a>참고 항목

- [Try...Catch...Finally 문](../language-reference/statements/try-catch-finally-statement.md)
